/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.Statement;
import ConnectionProvider.ConnectionProviderCode;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Rhythin
 */
public class AddAdmin extends javax.swing.JFrame {

    /**
     * Creates new form AddAdmin
     */
    public AddAdmin() {
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);
        scaleimage();
        setTitle("Add Admin");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    public void scaleimage(){
        BackgroundLabel.setPreferredSize(this.getPreferredSize());
        BackgroundLabel.setBounds(this.getBounds());
        ImageIcon icon= new ImageIcon(getClass().getResource("background.jpg"));
        Image img=icon.getImage();
        Image scaledImage = img.getScaledInstance(this.getWidth(), this.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon=new ImageIcon(scaledImage);
        BackgroundLabel.setIcon(scaledIcon);    
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userNameLabel = new javax.swing.JLabel();
        PasswordLabel = new javax.swing.JLabel();
        UserNameTextField = new javax.swing.JTextField();
        AddAdmin = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        PasswordField = new javax.swing.JPasswordField();
        BackgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(getPreferredSize());
        setMinimumSize(getPreferredSize());
        setPreferredSize(new java.awt.Dimension(550, 500));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userNameLabel.setText("User Name");
        userNameLabel.setMaximumSize(new java.awt.Dimension(150, 30));
        userNameLabel.setMinimumSize(new java.awt.Dimension(150, 30));
        userNameLabel.setPreferredSize(new java.awt.Dimension(150, 30));
        getContentPane().add(userNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 160, 30));

        PasswordLabel.setText("Password");
        PasswordLabel.setMaximumSize(new java.awt.Dimension(150, 30));
        PasswordLabel.setMinimumSize(new java.awt.Dimension(150, 30));
        PasswordLabel.setPreferredSize(new java.awt.Dimension(150, 30));
        getContentPane().add(PasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, -1));

        UserNameTextField.setMaximumSize(new java.awt.Dimension(150, 30));
        UserNameTextField.setMinimumSize(new java.awt.Dimension(150, 30));
        UserNameTextField.setPreferredSize(new java.awt.Dimension(150, 30));
        getContentPane().add(UserNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, -1, -1));

        AddAdmin.setText("Add Admin");
        AddAdmin.setMaximumSize(new java.awt.Dimension(150, 30));
        AddAdmin.setMinimumSize(new java.awt.Dimension(150, 30));
        AddAdmin.setPreferredSize(new java.awt.Dimension(150, 30));
        AddAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddAdminActionPerformed(evt);
            }
        });
        getContentPane().add(AddAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, -1, -1));

        ExitButton.setText("Exit");
        ExitButton.setMaximumSize(new java.awt.Dimension(150, 30));
        ExitButton.setMinimumSize(new java.awt.Dimension(150, 30));
        ExitButton.setPreferredSize(new java.awt.Dimension(150, 30));
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ExitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, -1, -1));

        PasswordField.setMaximumSize(new java.awt.Dimension(150, 30));
        PasswordField.setMinimumSize(new java.awt.Dimension(150, 30));
        PasswordField.setPreferredSize(new java.awt.Dimension(150, 30));
        getContentPane().add(PasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, -1, -1));

        BackgroundLabel.setText("jLabel1");
        BackgroundLabel.setPreferredSize(new java.awt.Dimension(100, 100));
        getContentPane().add(BackgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Admin frame=new Admin();
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void AddAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddAdminActionPerformed
        // TODO add your handling code here:
        String username=UserNameTextField.getText();
        String password=new String(PasswordField.getPassword());
        
        try {
            Connection con=ConnectionProviderCode.getcon();
            Statement st= con.createStatement();
            st.executeUpdate("insert into adminlogin values('"+ username+"', '"+password +"')");

        
            JOptionPane.showMessageDialog(null, "admin added successsfully");
            setVisible(false);
            AddAdmin frame=new AddAdmin();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }//GEN-LAST:event_AddAdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddAdmin;
    private javax.swing.JLabel BackgroundLabel;
    private javax.swing.JButton ExitButton;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JTextField UserNameTextField;
    private javax.swing.JLabel userNameLabel;
    // End of variables declaration//GEN-END:variables
}
