/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Rhythin
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        scaleimage();
        setTitle("Admin Page");
    }
    public void scaleimage(){
        BackgroundLabel.setPreferredSize(this.getPreferredSize());
        BackgroundLabel.setBounds(this.getBounds());
        ImageIcon icon= new ImageIcon(getClass().getResource("background.jpg"));
        Image img=icon.getImage();
        Image scaledImage = img.getScaledInstance(this.getWidth(), this.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon=new ImageIcon(scaledImage);
        BackgroundLabel.setIcon(scaledIcon);    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InsertStudentButton = new javax.swing.JButton();
        InsertResultButton = new javax.swing.JButton();
        ListStudentsButton = new javax.swing.JButton();
        ListResultsButton = new javax.swing.JButton();
        UpdateResultButton = new javax.swing.JButton();
        LogoutButton = new javax.swing.JButton();
        DeleteAdmin = new javax.swing.JButton();
        AddAdminButton = new javax.swing.JButton();
        DeleteStudentButton = new javax.swing.JButton();
        DeleteResult = new javax.swing.JButton();
        SetupButton = new javax.swing.JButton();
        BackgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(550, 400));
        setMinimumSize(new java.awt.Dimension(550, 400));
        setPreferredSize(new java.awt.Dimension(550, 500));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        InsertStudentButton.setText("Insert Student");
        InsertStudentButton.setMaximumSize(new java.awt.Dimension(150, 30));
        InsertStudentButton.setMinimumSize(new java.awt.Dimension(150, 30));
        InsertStudentButton.setPreferredSize(new java.awt.Dimension(150, 30));
        InsertStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertStudentButtonActionPerformed(evt);
            }
        });
        getContentPane().add(InsertStudentButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        InsertResultButton.setText("InsertResult");
        InsertResultButton.setMaximumSize(new java.awt.Dimension(150, 30));
        InsertResultButton.setMinimumSize(new java.awt.Dimension(150, 30));
        InsertResultButton.setPreferredSize(new java.awt.Dimension(150, 30));
        InsertResultButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertResultButtonActionPerformed(evt);
            }
        });
        getContentPane().add(InsertResultButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        ListStudentsButton.setText("List Students");
        ListStudentsButton.setMaximumSize(new java.awt.Dimension(150, 30));
        ListStudentsButton.setMinimumSize(new java.awt.Dimension(150, 30));
        ListStudentsButton.setPreferredSize(new java.awt.Dimension(150, 30));
        ListStudentsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListStudentsButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ListStudentsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, -1));

        ListResultsButton.setText("List Results");
        ListResultsButton.setMaximumSize(new java.awt.Dimension(150, 30));
        ListResultsButton.setMinimumSize(new java.awt.Dimension(150, 30));
        ListResultsButton.setPreferredSize(new java.awt.Dimension(150, 30));
        ListResultsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListResultsButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ListResultsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));

        UpdateResultButton.setText("Update Student Result");
        UpdateResultButton.setMaximumSize(new java.awt.Dimension(150, 30));
        UpdateResultButton.setMinimumSize(new java.awt.Dimension(150, 30));
        UpdateResultButton.setPreferredSize(new java.awt.Dimension(150, 30));
        UpdateResultButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateResultButtonActionPerformed(evt);
            }
        });
        getContentPane().add(UpdateResultButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, -1, -1));

        LogoutButton.setText("Logout");
        LogoutButton.setMaximumSize(new java.awt.Dimension(150, 30));
        LogoutButton.setMinimumSize(new java.awt.Dimension(150, 30));
        LogoutButton.setPreferredSize(new java.awt.Dimension(150, 30));
        LogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutButtonActionPerformed(evt);
            }
        });
        getContentPane().add(LogoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, -1, -1));

        DeleteAdmin.setText("Delete Admin");
        DeleteAdmin.setMaximumSize(new java.awt.Dimension(150, 30));
        DeleteAdmin.setMinimumSize(new java.awt.Dimension(150, 30));
        DeleteAdmin.setPreferredSize(new java.awt.Dimension(150, 30));
        DeleteAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteAdminActionPerformed(evt);
            }
        });
        getContentPane().add(DeleteAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, -1, -1));

        AddAdminButton.setText("Add Admin");
        AddAdminButton.setMaximumSize(new java.awt.Dimension(150, 30));
        AddAdminButton.setMinimumSize(new java.awt.Dimension(150, 30));
        AddAdminButton.setPreferredSize(new java.awt.Dimension(150, 30));
        AddAdminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddAdminButtonActionPerformed(evt);
            }
        });
        getContentPane().add(AddAdminButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, -1, -1));

        DeleteStudentButton.setText("Delete Student");
        DeleteStudentButton.setMaximumSize(new java.awt.Dimension(150, 30));
        DeleteStudentButton.setMinimumSize(new java.awt.Dimension(150, 30));
        DeleteStudentButton.setPreferredSize(new java.awt.Dimension(150, 30));
        DeleteStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteStudentButtonActionPerformed(evt);
            }
        });
        getContentPane().add(DeleteStudentButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, -1, -1));

        DeleteResult.setText("Delete Result");
        DeleteResult.setMaximumSize(new java.awt.Dimension(150, 30));
        DeleteResult.setMinimumSize(new java.awt.Dimension(150, 30));
        DeleteResult.setPreferredSize(new java.awt.Dimension(150, 30));
        DeleteResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteResultActionPerformed(evt);
            }
        });
        getContentPane().add(DeleteResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, -1, -1));

        SetupButton.setText("Setup");
        SetupButton.setMaximumSize(new java.awt.Dimension(150, 30));
        SetupButton.setMinimumSize(new java.awt.Dimension(150, 30));
        SetupButton.setPreferredSize(new java.awt.Dimension(150, 30));
        SetupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SetupButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SetupButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, -1, -1));

        BackgroundLabel.setText("jLabel1");
        getContentPane().add(BackgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ListStudentsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListStudentsButtonActionPerformed
        // TODO add your handling code here
        this.setVisible(false);
        ListStudents frame=new ListStudents();
    }//GEN-LAST:event_ListStudentsButtonActionPerformed

    private void InsertStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertStudentButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        InsertStudent frame=new InsertStudent();
    }//GEN-LAST:event_InsertStudentButtonActionPerformed

    private void UpdateResultButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateResultButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        UpdateResult frame=new UpdateResult();
    }//GEN-LAST:event_UpdateResultButtonActionPerformed

    private void InsertResultButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertResultButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        InsertResult frame=new InsertResult();
    }//GEN-LAST:event_InsertResultButtonActionPerformed

    private void LogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        HomePage frame=new HomePage();
    }//GEN-LAST:event_LogoutButtonActionPerformed

    private void ListResultsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListResultsButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        ListResults frame=new ListResults();
    }//GEN-LAST:event_ListResultsButtonActionPerformed

    private void DeleteStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteStudentButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        DeleteStudent frame=new DeleteStudent();
    }//GEN-LAST:event_DeleteStudentButtonActionPerformed

    private void DeleteResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteResultActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        DeleteResult frame= new DeleteResult();
    }//GEN-LAST:event_DeleteResultActionPerformed

    private void AddAdminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddAdminButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        AddAdmin frame=new AddAdmin();
    }//GEN-LAST:event_AddAdminButtonActionPerformed

    private void DeleteAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteAdminActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        DeleteAdmin frame=new DeleteAdmin();
    }//GEN-LAST:event_DeleteAdminActionPerformed

    private void SetupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SetupButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        SetupDatabase frame=new SetupDatabase();
    }//GEN-LAST:event_SetupButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddAdminButton;
    private javax.swing.JLabel BackgroundLabel;
    private javax.swing.JButton DeleteAdmin;
    private javax.swing.JButton DeleteResult;
    private javax.swing.JButton DeleteStudentButton;
    private javax.swing.JButton InsertResultButton;
    private javax.swing.JButton InsertStudentButton;
    private javax.swing.JButton ListResultsButton;
    private javax.swing.JButton ListStudentsButton;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JButton SetupButton;
    private javax.swing.JButton UpdateResultButton;
    // End of variables declaration//GEN-END:variables
}
