/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;


import java.sql.Connection;
import java.sql.Statement;
import ConnectionProvider.ConnectionProviderCode;
import java.awt.Image;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;


/**
 *
 * @author Rhythin
 */
public class InsertResult extends javax.swing.JFrame {

    /**
     * Creates new form InsertResult
     */
    public InsertResult() {
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        setTitle("Add Result");
        scaleimage();
    }
    public void scaleimage(){
        BackgroundLabel.setPreferredSize(this.getPreferredSize());
        BackgroundLabel.setBounds(this.getBounds());
        ImageIcon icon= new ImageIcon(getClass().getResource("background.jpg"));
        Image img=icon.getImage();
        Image scaledImage = img.getScaledInstance(this.getWidth(), this.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon=new ImageIcon(scaledImage);
        BackgroundLabel.setIcon(scaledIcon);    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RollNoLabel = new javax.swing.JLabel();
        rollNoTextField = new javax.swing.JTextField();
        SearchButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        PhysicsLabel = new javax.swing.JLabel();
        MathsLabel = new javax.swing.JLabel();
        ChemistryLabel = new javax.swing.JLabel();
        EletricalLabel = new javax.swing.JLabel();
        BiologyLabel = new javax.swing.JLabel();
        PhysicsTextField = new javax.swing.JTextField();
        MathsTextField = new javax.swing.JTextField();
        ChemistryTextField = new javax.swing.JTextField();
        EletricalTextField = new javax.swing.JTextField();
        BiologyTextField = new javax.swing.JTextField();
        SubmitButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        BackgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(550, 500));
        setMinimumSize(new java.awt.Dimension(550, 500));
        setPreferredSize(new java.awt.Dimension(550, 500));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RollNoLabel.setText("Roll No");
        RollNoLabel.setMaximumSize(new java.awt.Dimension(150, 30));
        RollNoLabel.setMinimumSize(new java.awt.Dimension(150, 30));
        RollNoLabel.setPreferredSize(new java.awt.Dimension(150, 30));
        getContentPane().add(RollNoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 160, 30));

        rollNoTextField.setMaximumSize(new java.awt.Dimension(150, 30));
        rollNoTextField.setMinimumSize(new java.awt.Dimension(150, 30));
        rollNoTextField.setPreferredSize(new java.awt.Dimension(150, 30));
        getContentPane().add(rollNoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, -1, -1));

        SearchButton.setText("Search");
        SearchButton.setMaximumSize(new java.awt.Dimension(150, 30));
        SearchButton.setMinimumSize(new java.awt.Dimension(150, 30));
        SearchButton.setPreferredSize(new java.awt.Dimension(150, 30));
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SearchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Name", "RollNo", "Gender", "Father's Name", "Course", "Branch"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 510, 60));

        PhysicsLabel.setText("Physics");
        PhysicsLabel.setMaximumSize(new java.awt.Dimension(150, 30));
        PhysicsLabel.setMinimumSize(new java.awt.Dimension(150, 30));
        PhysicsLabel.setPreferredSize(new java.awt.Dimension(150, 30));
        getContentPane().add(PhysicsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));

        MathsLabel.setText("Maths");
        MathsLabel.setMaximumSize(new java.awt.Dimension(150, 30));
        MathsLabel.setMinimumSize(new java.awt.Dimension(150, 30));
        MathsLabel.setPreferredSize(new java.awt.Dimension(150, 30));
        getContentPane().add(MathsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, -1));

        ChemistryLabel.setText("Chemistry");
        ChemistryLabel.setMaximumSize(new java.awt.Dimension(150, 30));
        ChemistryLabel.setMinimumSize(new java.awt.Dimension(150, 30));
        ChemistryLabel.setPreferredSize(new java.awt.Dimension(150, 30));
        getContentPane().add(ChemistryLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, -1, -1));

        EletricalLabel.setText("Eletrical");
        EletricalLabel.setMaximumSize(new java.awt.Dimension(150, 30));
        EletricalLabel.setMinimumSize(new java.awt.Dimension(150, 30));
        EletricalLabel.setPreferredSize(new java.awt.Dimension(150, 30));
        getContentPane().add(EletricalLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, -1, -1));

        BiologyLabel.setText("Biology");
        BiologyLabel.setMaximumSize(new java.awt.Dimension(150, 30));
        BiologyLabel.setMinimumSize(new java.awt.Dimension(150, 30));
        BiologyLabel.setPreferredSize(new java.awt.Dimension(150, 30));
        getContentPane().add(BiologyLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, -1, -1));

        PhysicsTextField.setMaximumSize(new java.awt.Dimension(150, 30));
        PhysicsTextField.setMinimumSize(new java.awt.Dimension(150, 30));
        PhysicsTextField.setPreferredSize(new java.awt.Dimension(150, 30));
        getContentPane().add(PhysicsTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, -1, -1));

        MathsTextField.setMaximumSize(new java.awt.Dimension(150, 30));
        MathsTextField.setMinimumSize(new java.awt.Dimension(150, 30));
        MathsTextField.setPreferredSize(new java.awt.Dimension(150, 30));
        getContentPane().add(MathsTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, -1, -1));

        ChemistryTextField.setMaximumSize(new java.awt.Dimension(150, 30));
        ChemistryTextField.setMinimumSize(new java.awt.Dimension(150, 30));
        ChemistryTextField.setPreferredSize(new java.awt.Dimension(150, 30));
        getContentPane().add(ChemistryTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, -1, -1));

        EletricalTextField.setMaximumSize(new java.awt.Dimension(150, 30));
        EletricalTextField.setMinimumSize(new java.awt.Dimension(150, 30));
        EletricalTextField.setPreferredSize(new java.awt.Dimension(150, 30));
        getContentPane().add(EletricalTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, -1, -1));

        BiologyTextField.setMaximumSize(new java.awt.Dimension(150, 30));
        BiologyTextField.setMinimumSize(new java.awt.Dimension(150, 30));
        BiologyTextField.setPreferredSize(new java.awt.Dimension(150, 30));
        getContentPane().add(BiologyTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, -1, -1));

        SubmitButton.setText("Submit");
        SubmitButton.setMaximumSize(new java.awt.Dimension(150, 30));
        SubmitButton.setMinimumSize(new java.awt.Dimension(150, 30));
        SubmitButton.setPreferredSize(new java.awt.Dimension(150, 30));
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SubmitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, -1, -1));

        ExitButton.setText("Exit");
        ExitButton.setMaximumSize(new java.awt.Dimension(150, 30));
        ExitButton.setMinimumSize(new java.awt.Dimension(150, 30));
        ExitButton.setPreferredSize(new java.awt.Dimension(150, 30));
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ExitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 420, -1, -1));

        BackgroundLabel.setText("jLabel1");
        getContentPane().add(BackgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        // search botton
        int rollNo=Integer.parseInt(rollNoTextField.getText());
        try{
            Connection con=ConnectionProviderCode.getcon();
            Statement st=con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE   ,ResultSet.CONCUR_UPDATABLE );
            ResultSet rs=st.executeQuery("SELECT * FROM STUDENT WHERE ROLLNO ="+rollNo);
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            if(!rs.first()){
                JOptionPane.showMessageDialog(null, "Enetered RollNo Dosen't Exsist");
            }
            else{
                rollNoTextField.setEditable(false);
            }
           
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }//GEN-LAST:event_SearchButtonActionPerformed

    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonActionPerformed
        // Submit Button
        int rollNo=Integer.parseInt(rollNoTextField.getText());
        int BiologyMarks=Integer.parseInt(BiologyTextField.getText());
        int chemMarks=Integer.parseInt(ChemistryTextField.getText());
        int eletricalMarks=Integer.parseInt(EletricalTextField.getText());
        int mathsMarks=Integer.parseInt(MathsTextField.getText());
        int physicsMarks=Integer.parseInt(PhysicsTextField.getText());
        int totalMarks=mathsMarks+chemMarks+eletricalMarks+BiologyMarks+physicsMarks;
        
        try{
            Connection con=ConnectionProviderCode.getcon();
            Statement st=con.createStatement();
            st.executeUpdate("INSERT INTO RESULT VALUES("+rollNo+","+physicsMarks+","+mathsMarks+","+chemMarks+","
                    +eletricalMarks+","+BiologyMarks+","+totalMarks+")");
            JOptionPane.showMessageDialog(null, "Results Inserted");
            setVisible(false);
            InsertResult frame=new InsertResult();
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.toString());
        }
        
    }//GEN-LAST:event_SubmitButtonActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        // exit button
        int option=JOptionPane.showConfirmDialog(null, "are you sure", 
                "Exit", JOptionPane.YES_NO_OPTION);
        if(option==JOptionPane.YES_OPTION){
            this.setVisible(false);
            Admin frame=new Admin();
        }
    }//GEN-LAST:event_ExitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsertResult().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackgroundLabel;
    private javax.swing.JLabel BiologyLabel;
    private javax.swing.JTextField BiologyTextField;
    private javax.swing.JLabel ChemistryLabel;
    private javax.swing.JTextField ChemistryTextField;
    private javax.swing.JLabel EletricalLabel;
    private javax.swing.JTextField EletricalTextField;
    private javax.swing.JButton ExitButton;
    private javax.swing.JLabel MathsLabel;
    private javax.swing.JTextField MathsTextField;
    private javax.swing.JLabel PhysicsLabel;
    private javax.swing.JTextField PhysicsTextField;
    private javax.swing.JLabel RollNoLabel;
    private javax.swing.JButton SearchButton;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField rollNoTextField;
    // End of variables declaration//GEN-END:variables
}
