/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;


import java.sql.Connection;
import java.sql.Statement;
import ConnectionProvider.ConnectionProviderCode;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Rhythin
 */
public class InsertStudent extends javax.swing.JFrame {

    /**
     * Creates new form InsertStudent
     */
    public InsertStudent() {
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        setTitle("Add Students");
        scaleimage();
    }
    public void scaleimage(){
        BackgroundLabel.setPreferredSize(this.getPreferredSize());
        BackgroundLabel.setBounds(this.getBounds());
        ImageIcon icon= new ImageIcon(getClass().getResource("background.jpg"));
        Image img=icon.getImage();
        Image scaledImage = img.getScaledInstance(this.getWidth(), this.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon=new ImageIcon(scaledImage);
        BackgroundLabel.setIcon(scaledIcon);    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NameLabel = new javax.swing.JLabel();
        RollnoLabel = new javax.swing.JLabel();
        GenderLabel = new javax.swing.JLabel();
        fathernameLabel = new javax.swing.JLabel();
        courseLabel = new javax.swing.JLabel();
        branchLabel = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        NameTextField = new javax.swing.JTextField();
        RollnoTextField = new javax.swing.JTextField();
        fatherNametextField = new javax.swing.JTextField();
        GenderComboBox = new javax.swing.JComboBox<>();
        CourseComboBox = new javax.swing.JComboBox<>();
        BranchComboBox = new javax.swing.JComboBox<>();
        BackgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(550, 500));
        setMinimumSize(new java.awt.Dimension(550, 500));
        setPreferredSize(new java.awt.Dimension(550, 500));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NameLabel.setText("Name");
        NameLabel.setMaximumSize(new java.awt.Dimension(150, 30));
        NameLabel.setMinimumSize(new java.awt.Dimension(150, 30));
        NameLabel.setPreferredSize(new java.awt.Dimension(150, 30));
        getContentPane().add(NameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, -1));

        RollnoLabel.setText("Roll No");
        RollnoLabel.setMaximumSize(new java.awt.Dimension(150, 30));
        RollnoLabel.setMinimumSize(new java.awt.Dimension(150, 30));
        RollnoLabel.setPreferredSize(new java.awt.Dimension(150, 30));
        getContentPane().add(RollnoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));

        GenderLabel.setText("Gender");
        GenderLabel.setMaximumSize(new java.awt.Dimension(150, 30));
        GenderLabel.setMinimumSize(new java.awt.Dimension(150, 30));
        GenderLabel.setPreferredSize(new java.awt.Dimension(150, 30));
        getContentPane().add(GenderLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));

        fathernameLabel.setText("Father's Name");
        fathernameLabel.setMaximumSize(new java.awt.Dimension(150, 30));
        fathernameLabel.setMinimumSize(new java.awt.Dimension(150, 30));
        fathernameLabel.setPreferredSize(new java.awt.Dimension(150, 30));
        getContentPane().add(fathernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 150, 30));

        courseLabel.setText("Course");
        courseLabel.setMaximumSize(new java.awt.Dimension(150, 30));
        courseLabel.setMinimumSize(new java.awt.Dimension(150, 30));
        courseLabel.setPreferredSize(new java.awt.Dimension(150, 30));
        getContentPane().add(courseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, -1, -1));

        branchLabel.setText("Branch");
        branchLabel.setMaximumSize(new java.awt.Dimension(150, 30));
        branchLabel.setMinimumSize(new java.awt.Dimension(150, 30));
        branchLabel.setPreferredSize(new java.awt.Dimension(150, 30));
        getContentPane().add(branchLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, -1, -1));

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(submitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, -1, -1));

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(exitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, -1, -1));

        NameTextField.setMaximumSize(new java.awt.Dimension(150, 30));
        NameTextField.setMinimumSize(new java.awt.Dimension(150, 30));
        NameTextField.setPreferredSize(new java.awt.Dimension(150, 30));
        NameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(NameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, -1));

        RollnoTextField.setMaximumSize(new java.awt.Dimension(150, 30));
        RollnoTextField.setMinimumSize(new java.awt.Dimension(150, 30));
        RollnoTextField.setPreferredSize(new java.awt.Dimension(150, 30));
        getContentPane().add(RollnoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, -1, -1));

        fatherNametextField.setMaximumSize(new java.awt.Dimension(150, 30));
        fatherNametextField.setMinimumSize(new java.awt.Dimension(150, 30));
        fatherNametextField.setPreferredSize(new java.awt.Dimension(150, 30));
        getContentPane().add(fatherNametextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, -1, -1));

        GenderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Others" }));
        GenderComboBox.setMaximumSize(new java.awt.Dimension(150, 30));
        GenderComboBox.setMinimumSize(new java.awt.Dimension(150, 30));
        GenderComboBox.setPreferredSize(new java.awt.Dimension(150, 30));
        getContentPane().add(GenderComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, -1, -1));

        CourseComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "B.tech", "M.tech" }));
        CourseComboBox.setMaximumSize(new java.awt.Dimension(150, 30));
        CourseComboBox.setMinimumSize(new java.awt.Dimension(150, 30));
        CourseComboBox.setPreferredSize(new java.awt.Dimension(150, 30));
        getContentPane().add(CourseComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, -1, -1));

        BranchComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mech", "Chem", "CS", "Arch" }));
        BranchComboBox.setMaximumSize(new java.awt.Dimension(150, 30));
        BranchComboBox.setMinimumSize(new java.awt.Dimension(150, 30));
        BranchComboBox.setPreferredSize(new java.awt.Dimension(150, 30));
        getContentPane().add(BranchComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, -1, -1));

        BackgroundLabel.setText("jLabel1");
        getContentPane().add(BackgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameTextFieldActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // submit button:
        String name=NameTextField.getText();
        int rollno=Integer.parseInt(RollnoTextField.getText());
        String gender=(String)GenderComboBox.getSelectedItem();
        String fathername=fatherNametextField.getText();
        String course=(String)CourseComboBox.getSelectedItem();
        String branch=(String)BranchComboBox.getSelectedItem();
        
        
        try{
            Connection con=ConnectionProviderCode.getcon();
            Statement st= con.createStatement();
            st.executeUpdate("insert into student values('"+ name + "', '" + rollno +"', '"+ gender +"', '"+ fathername +"', '"+ course +"', '"+ branch +"')");

        
            JOptionPane.showMessageDialog(null, "insertion successsfull");
            setVisible(false);
            InsertStudent frame=new InsertStudent();
         
        }
        catch(Exception excp){
            JOptionPane.showMessageDialog(null, excp.toString());
        }
        
    }//GEN-LAST:event_submitButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        int result=JOptionPane.showConfirmDialog(null, "are you sure?", "exit", JOptionPane.YES_NO_OPTION);
        
        if(result==JOptionPane.YES_OPTION){
            setVisible(false);
            Admin frame=new Admin();
            frame.setLocationRelativeTo(null);
            frame.setVisible(true);
        }
    }//GEN-LAST:event_exitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsertStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackgroundLabel;
    private javax.swing.JComboBox<String> BranchComboBox;
    private javax.swing.JComboBox<String> CourseComboBox;
    private javax.swing.JComboBox<String> GenderComboBox;
    private javax.swing.JLabel GenderLabel;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JTextField NameTextField;
    private javax.swing.JLabel RollnoLabel;
    private javax.swing.JTextField RollnoTextField;
    private javax.swing.JLabel branchLabel;
    private javax.swing.JLabel courseLabel;
    private javax.swing.JButton exitButton;
    private javax.swing.JTextField fatherNametextField;
    private javax.swing.JLabel fathernameLabel;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
