/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;


import ConnectionProvider.connectionDetails;
import java.awt.Desktop;
import java.awt.Image;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/**
 *
 * @author Rhythin
 */
public class SetupDatabase extends javax.swing.JFrame {

    /**
     * Creates new form SetupDatabase
     */
    public SetupDatabase() {
        initComponents();
        this.setVisible(true);
        setLocationRelativeTo(null);
        setTitle("Setup");
        scaleimage();
        
        ServerTextField.setText(connectionDetails.getServername());
        PortTextField.setText(connectionDetails.getPort());
        userTextField.setText(connectionDetails.getUsername());
        PasswordTextField.setText(connectionDetails.getPassowrd());
        ApplyButton.setEnabled(false);
        
        
    }
    
    public void scaleimage(){
        BackgroundLabel.setPreferredSize(this.getPreferredSize());
        BackgroundLabel.setBounds(this.getBounds());
        ImageIcon icon= new ImageIcon(getClass().getResource("background.jpg"));
        Image img=icon.getImage();
        Image scaledImage = img.getScaledInstance(this.getWidth(), this.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon=new ImageIcon(scaledImage);
        BackgroundLabel.setIcon(scaledIcon);    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TestButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        ApplyButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ServerTextField = new javax.swing.JTextField();
        PortTextField = new javax.swing.JTextField();
        PasswordTextField = new javax.swing.JTextField();
        userTextField = new javax.swing.JTextField();
        DefaultButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        HelpButton = new javax.swing.JButton();
        BackgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(550, 500));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TestButton.setText("Test");
        TestButton.setPreferredSize(new java.awt.Dimension(150, 30));
        TestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TestButtonActionPerformed(evt);
            }
        });
        getContentPane().add(TestButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, -1, -1));

        ExitButton.setText("Exit");
        ExitButton.setPreferredSize(new java.awt.Dimension(150, 30));
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ExitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 410, -1, -1));

        ApplyButton.setText("Apply");
        ApplyButton.setPreferredSize(new java.awt.Dimension(150, 30));
        ApplyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApplyButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ApplyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, -1, -1));

        jLabel1.setText("Server");
        jLabel1.setPreferredSize(new java.awt.Dimension(150, 30));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));

        jLabel2.setText("Port");
        jLabel2.setPreferredSize(new java.awt.Dimension(150, 30));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, -1));

        jLabel4.setText("username");
        jLabel4.setPreferredSize(new java.awt.Dimension(150, 30));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, -1));

        jLabel5.setText("password");
        jLabel5.setPreferredSize(new java.awt.Dimension(150, 30));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));

        ServerTextField.setPreferredSize(new java.awt.Dimension(150, 30));
        getContentPane().add(ServerTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, -1, -1));

        PortTextField.setPreferredSize(new java.awt.Dimension(150, 30));
        getContentPane().add(PortTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, -1, -1));

        PasswordTextField.setPreferredSize(new java.awt.Dimension(150, 30));
        getContentPane().add(PasswordTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, -1, -1));

        userTextField.setPreferredSize(new java.awt.Dimension(150, 30));
        getContentPane().add(userTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, -1, -1));

        DefaultButton.setText("Set Default Values");
        DefaultButton.setPreferredSize(new java.awt.Dimension(150, 30));
        DefaultButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DefaultButtonActionPerformed(evt);
            }
        });
        getContentPane().add(DefaultButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, -1, -1));

        jLabel3.setText("If database is not setup pelase follow instructions given in help");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 290, 20));

        HelpButton.setText("Help");
        HelpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HelpButtonActionPerformed(evt);
            }
        });
        getContentPane().add(HelpButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, -1, -1));

        BackgroundLabel.setText("jLabel6");
        getContentPane().add(BackgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HelpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HelpButtonActionPerformed
        // TODO add your handling code here:
        try {
            
            Desktop.getDesktop().browse(new URL(GUI.Help.getUrl()).toURI());
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }//GEN-LAST:event_HelpButtonActionPerformed

    private void ApplyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApplyButtonActionPerformed
        // TODO add your handling code here:
        connectionDetails.setServername(ServerTextField.getText());
        connectionDetails.setPort(PortTextField.getText());
        connectionDetails.setUsername(userTextField.getText());
        connectionDetails.setPassowrd(PasswordTextField.getText());
        
        JOptionPane.showMessageDialog(null, "Details updated");
    }//GEN-LAST:event_ApplyButtonActionPerformed

    private void DefaultButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DefaultButtonActionPerformed
        // TODO add your handling code here:
        connectionDetails.setdefault();
        JOptionPane.showMessageDialog(null, "reverted to default options");
        this.setVisible(false);
        SetupDatabase frame=new SetupDatabase();
    }//GEN-LAST:event_DefaultButtonActionPerformed

    private void TestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TestButtonActionPerformed
        // TODO add your handling code here:
        try {
            String server=ServerTextField.getText();
            String port=PortTextField.getText();
            String user=userTextField.getText();
            String password=PasswordTextField.getText();
            
            boolean result=ConnectionProvider.Testconnection.test(server, port, user, password);
            
            if(result){
                ServerTextField.setEditable(false);
                PortTextField.setEditable(false);
                userTextField.setEditable(false);
                PasswordTextField.setEditable(false);
                
                ApplyButton.setEnabled(true);
   
            }
            else{
                JOptionPane.showMessageDialog(null, "Test Failed");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }//GEN-LAST:event_TestButtonActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SetupDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SetupDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SetupDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SetupDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SetupDatabase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ApplyButton;
    private javax.swing.JLabel BackgroundLabel;
    private javax.swing.JButton DefaultButton;
    private javax.swing.JButton ExitButton;
    private javax.swing.JButton HelpButton;
    private javax.swing.JTextField PasswordTextField;
    private javax.swing.JTextField PortTextField;
    private javax.swing.JTextField ServerTextField;
    private javax.swing.JButton TestButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField userTextField;
    // End of variables declaration//GEN-END:variables
}
