/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import ConnectionProvider.ConnectionProviderCode;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Rhythin
 */
public class UpdateResult extends javax.swing.JFrame {

    /**
     * Creates new form UpdateResult
     */
    public UpdateResult() {
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);
        SubmitButton.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        rollNoTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        PhysicsTextField = new javax.swing.JTextField();
        MathsTextField = new javax.swing.JTextField();
        ChemistryTextField = new javax.swing.JTextField();
        EletricalTextField = new javax.swing.JTextField();
        BiologyTextField = new javax.swing.JTextField();
        SubmitButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(550, 500));
        setMinimumSize(new java.awt.Dimension(550, 500));
        setPreferredSize(new java.awt.Dimension(550, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("RollNo");
        jLabel1.setMaximumSize(new java.awt.Dimension(150, 30));
        jLabel1.setMinimumSize(new java.awt.Dimension(150, 30));
        jLabel1.setPreferredSize(new java.awt.Dimension(150, 30));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 110, 30));

        rollNoTextField.setMaximumSize(new java.awt.Dimension(150, 30));
        rollNoTextField.setMinimumSize(new java.awt.Dimension(150, 30));
        rollNoTextField.setPreferredSize(new java.awt.Dimension(150, 30));
        getContentPane().add(rollNoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, -1, -1));

        jButton1.setText("Search");
        jButton1.setMaximumSize(new java.awt.Dimension(150, 30));
        jButton1.setMinimumSize(new java.awt.Dimension(150, 30));
        jButton1.setPreferredSize(new java.awt.Dimension(150, 30));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, -1, -1));

        jLabel2.setText("Physics");
        jLabel2.setMaximumSize(new java.awt.Dimension(150, 30));
        jLabel2.setMinimumSize(new java.awt.Dimension(150, 30));
        jLabel2.setPreferredSize(new java.awt.Dimension(150, 30));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, -1));

        jLabel3.setText("Maths");
        jLabel3.setMaximumSize(new java.awt.Dimension(150, 30));
        jLabel3.setMinimumSize(new java.awt.Dimension(150, 30));
        jLabel3.setPreferredSize(new java.awt.Dimension(150, 30));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

        jLabel4.setText("Chemistry");
        jLabel4.setMaximumSize(new java.awt.Dimension(150, 30));
        jLabel4.setMinimumSize(new java.awt.Dimension(150, 30));
        jLabel4.setPreferredSize(new java.awt.Dimension(150, 30));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, -1));

        jLabel5.setText("Eletrical");
        jLabel5.setMaximumSize(new java.awt.Dimension(150, 30));
        jLabel5.setMinimumSize(new java.awt.Dimension(150, 30));
        jLabel5.setPreferredSize(new java.awt.Dimension(150, 30));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, -1, -1));

        jLabel6.setText("Biology");
        jLabel6.setMaximumSize(new java.awt.Dimension(150, 30));
        jLabel6.setMinimumSize(new java.awt.Dimension(150, 30));
        jLabel6.setPreferredSize(new java.awt.Dimension(150, 30));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, -1, -1));

        PhysicsTextField.setMaximumSize(new java.awt.Dimension(150, 30));
        PhysicsTextField.setMinimumSize(new java.awt.Dimension(150, 30));
        PhysicsTextField.setPreferredSize(new java.awt.Dimension(150, 30));
        PhysicsTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhysicsTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(PhysicsTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, -1, -1));

        MathsTextField.setMaximumSize(new java.awt.Dimension(150, 30));
        MathsTextField.setMinimumSize(new java.awt.Dimension(150, 30));
        MathsTextField.setPreferredSize(new java.awt.Dimension(150, 30));
        getContentPane().add(MathsTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, -1, -1));

        ChemistryTextField.setMaximumSize(new java.awt.Dimension(150, 30));
        ChemistryTextField.setMinimumSize(new java.awt.Dimension(150, 30));
        ChemistryTextField.setPreferredSize(new java.awt.Dimension(150, 30));
        getContentPane().add(ChemistryTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, -1, -1));

        EletricalTextField.setMaximumSize(new java.awt.Dimension(150, 30));
        EletricalTextField.setMinimumSize(new java.awt.Dimension(150, 30));
        EletricalTextField.setPreferredSize(new java.awt.Dimension(150, 30));
        getContentPane().add(EletricalTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, -1, -1));

        BiologyTextField.setMaximumSize(new java.awt.Dimension(150, 30));
        BiologyTextField.setMinimumSize(new java.awt.Dimension(150, 30));
        BiologyTextField.setPreferredSize(new java.awt.Dimension(150, 30));
        getContentPane().add(BiologyTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, -1, -1));

        SubmitButton.setText("Submit");
        SubmitButton.setMaximumSize(new java.awt.Dimension(150, 30));
        SubmitButton.setMinimumSize(new java.awt.Dimension(150, 30));
        SubmitButton.setPreferredSize(new java.awt.Dimension(150, 30));
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SubmitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, -1, -1));

        ExitButton.setText("Exit");
        ExitButton.setMaximumSize(new java.awt.Dimension(150, 30));
        ExitButton.setMinimumSize(new java.awt.Dimension(150, 30));
        ExitButton.setPreferredSize(new java.awt.Dimension(150, 30));
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ExitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 420, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int rollNo=Integer.parseInt(rollNoTextField.getText());
        try{
            Connection con=ConnectionProviderCode.getcon();
            Statement st=con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE   ,ResultSet.CONCUR_UPDATABLE );
            ResultSet rs=st.executeQuery("SELECT * FROM RESULT WHERE ROLLNO ="+rollNo);
            if(!rs.first()){
                JOptionPane.showMessageDialog(null, "Enetered RollNo Dosen't Exsist");
            }
            else{
                rollNoTextField.setEditable(false);
                PhysicsTextField.setText(rs.getString(2));
                MathsTextField.setText(rs.getString(3));
                ChemistryTextField.setText(rs.getString(4));
                EletricalTextField.setText(rs.getString(5));
                BiologyTextField.setText(rs.getString(6));
                
                rollNoTextField.setEditable(false);
                SubmitButton.setEnabled(true);
            }
           
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void PhysicsTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhysicsTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhysicsTextFieldActionPerformed

    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonActionPerformed
        // TODO add your handling code here:
        int rollNo=Integer.parseInt(rollNoTextField.getText());
        int BiologyMarks=Integer.parseInt(BiologyTextField.getText());
        int chemMarks=Integer.parseInt(ChemistryTextField.getText());
        int eletricalMarks=Integer.parseInt(EletricalTextField.getText());
        int mathsMarks=Integer.parseInt(MathsTextField.getText());
        int physicsMarks=Integer.parseInt(PhysicsTextField.getText());
        int totalMarks=mathsMarks+chemMarks+eletricalMarks+BiologyMarks+physicsMarks;
        
        try{
            Connection con=ConnectionProviderCode.getcon();
            Statement st=con.createStatement();
            st.executeUpdate("UPDATE RESULT SET PHYSICS="+physicsMarks+", MATHS="+mathsMarks+", CHEMISTRY="+chemMarks+
                    ",ELETRICAL="+eletricalMarks+",BIOLOGY="+BiologyMarks+",TOTAL="+totalMarks+" WHERE ROLLNO="+rollNo);
            JOptionPane.showMessageDialog(null, "Results updated successfully");
            setVisible(false);
            
            UpdateResult frame=new UpdateResult();
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }//GEN-LAST:event_SubmitButtonActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Admin frame=new Admin();
    }//GEN-LAST:event_ExitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateResult().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BiologyTextField;
    private javax.swing.JTextField ChemistryTextField;
    private javax.swing.JTextField EletricalTextField;
    private javax.swing.JButton ExitButton;
    private javax.swing.JTextField MathsTextField;
    private javax.swing.JTextField PhysicsTextField;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField rollNoTextField;
    // End of variables declaration//GEN-END:variables
}
